language: node_js

node_js:
    - "0.10"
    - "0.12"
    - "4.2"

env:
  global:
    - GH_REF: github.com/maxvipon/priv-js.git
    - ISTANBUL_COVERAGE: yes

branches:
  only:
    - master

after_success:
  - npm i coveralls
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && echo "Coverage data was sent to coveralls!"
